spring.application.name=backend_tesis


#Claves cifrado
security.token.sesion=${SECURITY_TOKEN_SESION:PW#dkfjdsEIDK_KDsdf6786FHSDF-$FBJDFBA-9847838-#calveSuperScreta1267@34hjdsd##Fkjfnb@}

//PW#dkfjdsEIDK_KDsdf6786FHSDF-$FBJDFBA-9847838-#calveSuperScreta1267@34hjdsd##Fkjfnb@

#Puerto
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/API/tesis

#RUTAS
auth.url=${AUTH_URL:http://localhost:5050/API/tesis/}
motor.url=${MOTOR_URL:http://localhost:5041/API/tesis/}
correo.url=${CORREO_URL:http://localhost:8282/API/tesis/}
corsorigin.url=${CORSORIGIN_URL:http://localhost:4200}

#CREDENCIALES AWS






#CONECCION BASE DATOS
#spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/repaso}
#spring.datasource.username=${POSTGRES_USER:postgres}
#spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://dpg-d1g3j9vgi27c73eefi60-a.oregon-postgres.render.com/pruebatesis_g132}
spring.datasource.username=${POSTGRES_USER:pgadmin}
spring.datasource.password=${POSTGRES_PASSWORD:S5wlPKGH8bUiStdXm8T3zcF9BGXsosOr}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.discovery.enabled=false

# Actuator (para Consul)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
