spring.application.name=backend_tesis

#Puerto
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/API/tesis

#RUTAS
auth.url=${AUTH_URL:http://autenticacion:8080/API/tesis/}
motor.url=${MOTOR_URL:http://motor-procesos:8080/API/tesis/}
correo.url=${CORREO_URL:http://correo:8080/API/tesis/}
corsorigin.url=${CORSORIGIN_URL:http://tesis.local}

#CREDENCIALES AWS
aws.accessKeyId=${AWS_ACCESS_KEY_ID:test}
aws.secretKey=${AWS_SECRET_ACCESS_KEY:test}
aws.region=${AWS_DEFAULT_REGION:us-east-1}

#CONECCION BASE DATOS
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/base_tesis}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cloud.discovery.enabled=false

# Actuator (para Consul)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
