spring.application.name=autenticacion

#Puertto
server.port=${SERVER_PORT:5050}
server.servlet.context-path=/API/tesis



# Actuator (para Consul)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always