spring.application.name=autenticacion

#Puerto
server.port=${SERVER_PORT:5050}
server.servlet.context-path=/API/tesis
corsorigin.url=${CORSORIGIN_URL:http://localhost:4200}


security.token.key=${SECURITY_TOKEN_SESION:PW#dkfjdsEIDK_KDsdf6786FHSDF-$FBJDFBA-9847838-#calveSuperScreta1267@34hjdsd##Fkjfnb@}
security.token.sesion=${SECURITY_TOKEN_SESION:PW#dkfjdsEIDK_KDsdf6786FHSDF-$FBJDFBA-9847838-#calveSuperScreta1267@34hjdsd##Fkjfnb@}



# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
