server.servlet.context-path=/API/tesis/
spring.sendgrid.api-key= frfgdfgdfgd
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=luismosquera97@gmail.com
spring.mail.password=jtnlbwbzfcljuqbi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailgun.apiKey=3f142459cb0c2d51aeb2438c3e213a98-f6202374-3e7cfca5
mailgun.sandboxDomain=sandbox8139c39bf5cd47f8bfb6633558301db9.mailgun.org
mailgun.fromEmail=postmaster@sandbox8139c39bf5cd47f8bfb6633558301db9.mailgun.org
server.port=8282
